language: objective-c
osx_image: xcode9
xcode_workspace: saml-ios-app.xcworkspace
xcode_scheme: saml-ios-app
xcode_sdk: iphonesimulator

before_install:
  - travis_wait pod repo update --silent

notifications:
  irc: "irc.freenode.org#feedhenry"

script:
  - xcodebuild clean build -workspace saml-ios-app.xcworkspace -scheme saml-ios-app -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
branches:
  only:
    - master
    - ios11
